# Generated by Django 5.1.5 on 2025-03-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stopBApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
