# Generated by Django 5.2 on 2025-04-10 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopBApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBusLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('bus_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='stopBApp.busline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_bus_lines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
