# Generated by Django 5.1.6 on 2025-04-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopBApp', '0002_savedbusline'),
    ]

    operations = [
        migrations.AddField(
            model_name='busline',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busline',
            name='route_id',
            field=models.CharField(default='UNKNOWN', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busline',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
